theme: jekyll-theme-console
markdown: kramdown
highlighter: rouge
header_pages:
  - index.md
  - about.md

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)
